### ISSUE TITLE
Chocolatey package missing for v6.2.0

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [ChangemakerStudios/Papercut-SMTP#264]
**Describe the bug**

The package on the Chocolatey Community Repository is still at v6.0.0

**To Reproduce**
1. `choco upgrade papercut`
2. Check the version, still at v6.0.0

**Expected behavior**

The package Chocolatey Community Repository is up to date.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10 22H2

**Additional context**

N/A

**Comment by Jaben** [comment]
I'm not going to support Chocolately going forward -- I'll maybe create a winget install -- but my time is limited.

**Comment by Jaben** [comment]
> > I'm not going to support Chocolately going forward
> 
> @Jaben Can I ask why you're not considering a Chocolatey package going forward? This question isn't intended to push you in that direction, but to understand why you are no longer considering that, but are considering other platforms.

Thanks for reaching out.

The most recent attempts to automate releases to Chocolately have been met with too many manual interventions/blocks and in some cases being marked as (false-positive) with viruses. Also, it's been hard finding examples of working Chocolatey packages.  Maybe my information is out of date -- I haven't updated chocolate in a while due to the above problems. I don't have time/effort to figure out what needs to be done every time and manually intervene.
